export enum categoryReducerDefault {
  FETCH_CATEGORIES_START = "category/FETCH_CATEGORY_START",
  FETCH_CATEGORIES_SUCCESS = "category/FETCH_CATEGORY_SUCCESS",
  FETCH_CATEGORIES_FAILED = "category/FETCH_CATEGORY_FAILED",
}
